
// Define project highlights data with more detailed case studies
export const projectHighlights = [
  {
    id: 7,
    title: "GreyMatters Studio – Automated Lead Pipeline",
    shortDescription: "Building a fully automated lead pipeline in Go High Level for a mental health studio",
    description: "Developed a comprehensive automation system for neurofeedback lead nurturing, tracking, and conversion, resulting in 3x increase in bookings.",
    image: `https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80`,
    category: "CRM Automation",
    technologies: ["Go High Level", "Email Automation", "Funnel Building", "Lead Tracking"],
    relatedService: "workflows",
    clientName: "GreyMatters Studio",
    challenge: "GreyMatters Studio needed a way to automate lead nurturing for their neurofeedback services. Their team was overwhelmed with manual follow-ups and lacked a proper system to track leads downloading their free resources.",
    solution: "Built a customized funnel inside Go High Level that captured users who downloaded the Brain Users Handbook. Created a tagging system for segmenting leads. Developed a pipeline stage inside 'Patient Pipeline' to track progress. Designed a 12-week automated email workflow that delivered weekly education-based content.",
    results: "3x increase in bookings within 6 weeks of implementation. 48% average open rate across the nurturing sequence. Reduced administrative workload by 70%, allowing the team to focus on client care."
  },
  {
    id: 1,
    title: "Triad Diagnostic Solutions - Redesign",
    shortDescription: "Complete rebrand and website overhaul with CRM integration",
    description: "Full website redesign with custom inventory system and customer portal integration. Added automated workflows for inventory management and order processing.",
    image: `https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80`,
    category: "Web Development",
    technologies: ["Go High Level", "WordPress", "WooCommerce", "JavaScript"],
    relatedService: "workflows",
    clientName: "Triad Diagnostic Solutions",
    challenge: "The client had an outdated website with manual inventory tracking that was causing errors and delays. Customer service was overwhelmed with basic inquiries.",
    solution: "Implemented a modern responsive website with inventory management system and customer portal. Created automated workflows for order processing and customer notifications.",
    results: "Inventory errors reduced by 95%, customer service inquiries reduced by 60%, and order processing time cut by 75%."
  },
  {
    id: 2,
    title: "All Pro - Service Booking System",
    shortDescription: "HVAC service scheduling system with automated follow-ups",
    description: "Built an integrated service booking system with customer notifications, technician scheduling, and automated follow-up sequences to improve customer retention.",
    image: `https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80`,
    category: "Automation",
    technologies: ["Go High Level", "Twilio", "Zapier", "Calendar API"],
    relatedService: "workflows",
    clientName: "All Pro Heating & Cooling",
    challenge: "Technicians were double-booked, customers experienced long wait times, and follow-up appointments were frequently missed.",
    solution: "Developed an integrated booking system with automated confirmations, reminders, and technician assignment. Created a follow-up sequence for maintenance reminders.",
    results: "Reduced scheduling errors by 100%, decreased no-shows by 75%, and increased recurring maintenance appointments by 45%."
  },
  {
    id: 3,
    title: "Grey Matters - SEO & Content Strategy",
    shortDescription: "Complete SEO overhaul for mental health services",
    description: "Comprehensive SEO audit and implementation for a mental health studio, resulting in 300% increase in organic traffic and first-page rankings for key terms.",
    image: `https://images.unsplash.com/photo-1487058792275-0ad4aaf24ca7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80`,
    category: "SEO",
    technologies: ["Google Analytics", "SEMrush", "Ahrefs", "Content Strategy"],
    relatedService: "seo-audits",
    clientName: "Grey Matters",
    challenge: "Despite offering excellent services, the client was virtually invisible in search results and struggling to attract new patients.",
    solution: "Conducted comprehensive keyword research, implemented technical SEO fixes, created an ongoing content strategy focused on mental health topics, and built quality backlinks.",
    results: "Achieved first page rankings for 28 target keywords, increased organic traffic by 300%, and doubled monthly new patient inquiries."
  },
  {
    id: 4,
    title: "Pure Water - E-commerce Sales Funnel",
    shortDescription: "High-converting funnel for bottleless water coolers",
    description: "Designed and implemented a multi-step sales funnel for a bottleless water cooler company, increasing lead conversion rate by 45% and reducing customer acquisition cost.",
    image: `https://images.unsplash.com/photo-1605810230434-7631ac76ec81?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80`,
    category: "Funnel Development",
    technologies: ["Go High Level", "Facebook Ads", "Google Ads", "Email Automation"],
    relatedService: "funnels",
    clientName: "Pure Water",
    challenge: "High ad spend was not resulting in enough qualified leads or sales. The sales process was unclear and lacked proper follow-up.",
    solution: "Created a multi-step funnel with educational content, qualification questions, and automated follow-up sequences. Integrated with ad platforms for retargeting.",
    results: "Reduced cost per acquisition by 38%, increased lead-to-sale conversion by 45%, and improved average order value by 22%."
  },
  {
    id: 5,
    title: "March On Mission - Email Campaign",
    shortDescription: "Nonprofit donation email sequence with storytelling",
    description: "Crafted a compelling email campaign for a nonprofit, featuring personal stories and impact metrics that resulted in a 28% increase in donations from email channels.",
    image: `https://images.unsplash.com/photo-1461749280684-dccba630e2f6?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80`,
    category: "Email Marketing",
    technologies: ["Mailchimp", "Copy Writing", "A/B Testing", "Segmentation"],
    relatedService: "email-marketing",
    clientName: "March on Mission",
    challenge: "The organization had a large email list but low engagement and donation rates. Messages lacked personal connection and clear calls to action.",
    solution: "Developed a storytelling-based email series highlighting individual impact stories, implemented A/B testing for subject lines, and created segmented donor journeys.",
    results: "Improved email open rates by 65%, click-through rates by 43%, and increased donation revenue from email by 28%."
  },
  {
    id: 6,
    title: "GetSAID - AI Support Chatbot",
    shortDescription: "Custom AI chatbot for intelligent customer support",
    description: "Developed and deployed an intelligent chatbot handling customer inquiries, appointment booking, and lead qualification without human intervention.",
    image: `https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80`,
    category: "AI Development",
    technologies: ["Go High Level", "OpenAI", "NLP", "Automation"],
    relatedService: "ai-chatbot",
    clientName: "GetSAID",
    challenge: "Support team was overwhelmed with basic questions and booking requests. Lead qualification was inconsistent and often incomplete.",
    solution: "Implemented an AI-powered chatbot that handles common questions, books appointments, and qualifies leads based on custom criteria before handing off to human agents.",
    results: "Reduced support tickets by 65%, increased after-hours lead capture by 100%, and improved lead qualification accuracy by 40%."
  }
];
